### ISSUE TITLE
[10.0] Any Plans For A 10.0 Version?

### ISSUE THREAD

**Issue by lukebranch** [abakus-it-old/report_agedbalancedetail#1]
@bernarddelhez ,

Thanks for building this module, it's really good to see these features in a community module!

Any plans to port this to version 10.0? I would just like to check as I may submit a PR for 10.0 if you do not have any plans to port to version 10.0 in the near future.

**Comment by bernarddelhez** [comment]
I will not port this module to version 10.0 in the near future.
